### ISSUE TITLE
Openstack Contributor 등록

### ISSUE THREAD

**Issue by ghost** [openstack-kr/study-contributors#1]
스터디 멤버들이 Openstack Contributor 로 등록하고 테스트에 성공한다. 

테스트 방법: ssh -p 29418 아이디@review.openstack.org

**Comment by ghost** [comment]
다른계정이 있긴한데, 연습삼아서 새롭게 등록 해봤습니다. :D 

https://launchpad.net/~donghwi-cha

**Comment by JohnHaan** [comment]
한승진입니다. 제런치패드 주소입니다
https://launchpad.net/~yongiman

**Comment by kkd927** [comment]
권경덕입니다. 제 런치패드 주소 입니다~
https://launchpad.net/~kkd927

**Comment by jazzsir** [comment]
서한배입니다. 등록하였습니다. :)
https://launchpad.net/~jazzsir

**Comment by JonghanPark** [comment]
박종한입니다. 등록했습니다.
https://launchpad.net/~forhim-park

**Comment by seungbum** [comment]
주승범입니다. 등록했습니다.^^
https://launchpad.net/~seungbum-ju

**Comment by phs2131** [comment]
박형석 입니다. 등록 완료했습니다. ;-)
https://launchpad.net/~nicholas-hpark

**Comment by elinjkim** [comment]
김지은 입니다. 등록했습니다 :)
https://launchpad.net/~jekim

**Comment by cosmos0703** [comment]
박인혜입니다. 런치패드주소입니다
https://launchpad.net/~cosmos0703
