### ISSUE TITLE
magnum 개발 환경 구축 

### ISSUE THREAD

**Issue by ghost** [openstack-kr/study-contributors#6]
devstack을 이용한 기본적인 개발 환경 (devstack + editor 또는 각자 쓰는 ide)

**Comment by ghost** [comment]
차동휘입니다. fedora 21에 devstack으로 완료했습니다. ^^

**Comment by JohnHaan** [comment]
한승진입니다. 설치는완료했고 설정만 남았습니다

**Comment by elinjkim** [comment]
cmm_devstart, cmm_magstart 창을 띄운 후, 아톰 에디터까지는 열어보았습니다.

**Comment by kkd927** [comment]
권경덕입니다. 주신 VM이미지를 통해 완료하였습니다.

**Comment by jazzsir** [comment]
서한배입니다. 배포 이미지로 개발환경 세팅 하였습니다. 감사합니다.~

**Comment by phs2131** [comment]
박형석 입니다.
배포한 이미지로 개발환경 확인 완료 하였습니다.
추가적으로 직접 CentOS7환경으로 구성해보고 있습니다.

**Comment by JonghanPark** [comment]
저는 CentOS7 기반으로 만들었고, 배포해주신 image도 따로 설정해 봤습니다.
개발환경은.. nfs로 붙여서 Host에서 pycharm과 geany로.. ㅎ
